name: Run API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'maven'
          maven-version: '3.8.4'

      - name: Install Dependencies
        run: mvn clean install -U -DskipTests

      - name: Run API Tests
        run: mvn test -Dtest=runners.TestRunner
